[features]
seeds = false
skip-lint = false
[programs.localnet]
hyperion = "3A6B3ELfxPn7M1mbof29kr9KiejFzuY488T9aTYZi6Cs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/nico/.config/solana/mainnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
